### ISSUE TITLE
DynamicPatcher 2.1 with Dionysus 0.1  示例的脚本不能正常使用？

### ISSUE THREAD

**Issue by zhaihs** [Xkein/YRDynamicPatcher#11]
下载了DynamicPatcher 2.1 with Dionysus 0.1的文件DP-Dionysus.0.114514.zip，
我删除了游戏目录里原来的DynamicPatcher文件和DynamicPatcher 目录后，把DP-Dionysus.0.114514目录里的文件拷贝过去。
但是按照示例里的
[MTNK]
Scripts=MTNKScript.cs
FireSuperWeapon=NukeSpecial
写入规则文件后，脚本调用失败，请问是哪里的问题。还是说DP-Dionysus.0.114514  目录里的文件存放路径不对？

**Comment by zhaihs** [comment]
[CTNK]:[HTNK]
Scripts=MTNKScript
FireSuperWeapon=NukeSpecial

仔细看了命令行里的日志，相关提示是这样的：
compiling: D:\GAME\ares\DynamicPatcher\Scripts\MTNKScript.cs
code is older than assembly, use old assembly.

packing D:\GAME\ares\DynamicPatcher\Build\Scripts\MTNKScript.tmp into D:\GAME\ares\DynamicPatcher\Packages\Build\Scripts\MTNKScript.pkg

appling: MTNKScript, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
-----------------------------------
in class Scripts.MTNK:

[Error] ScriptManager could not find script: MTNKScript

**Comment by Xkein** [comment]
没看出有什么问题，你还是加qq群（820888931）进来细说吧
