### ISSUE TITLE
关于动态INI的问题

### ISSUE THREAD

**Issue by Mrzhengsix** [Xkein/YRDynamicPatcher#9]
首先支持作者，干得好！
关于动态INI有几个问题想反馈：
1、首先是意料之外的偶然不加载子ini，即便在rulesmd.ini或者artmd.ini中的[#include]注册后依然如此，提示“not support ini”，这是我的疑问1；
2、其次是动态注册anim以后似乎并不能生效，素材文件等可以即时读取，如果是bug希望作者能够修复，如果是我的使用方式问题请作者指正，本身动态ini就是一个十分令人兴奋的事情，能够动态地完全体地添加一个单位或者是武器更是一件令人激动地事情，这是我的疑问2;

我的做法通常是：将一个单位的rules和art分别写在两个ini中放置game根目录，把注册的节点写在另一个ini中，分别在rulesmd.ini或者artmd.ini中的[#include]下进行注册，然后回到游戏。

再次支持！Thx

**Comment by Xkein** [comment]
谢谢反馈，动态INI是个十分复杂的功能，真要完善将会有很大的工作量，目前很难做到兼顾所有需求，不过日后我会慢慢添砖加瓦，修复bug。
另外，本库不包含该内容，请到[Dionysus](https://github.com/Xkein/DPExtension-Dionysus)这里提交本issue

**Comment by Xkein** [comment]
谢谢反馈，动态INI是个十分复杂的功能，真要完善将会有很大的工作量，目前很难做到兼顾所有需求，不过日后我会慢慢添砖加瓦，修复bug。
另外，本库不包含该内容，请到[Dionysus](https://github.com/Xkein/DPExtension-Dionysus)这里提交本issue
